mongodb:
  host: localhost
  port: 27017
  authentication-database: admin
  database: configuration
  username: root
  password: q8SFbdesFv

minio:
  host: localhost
  port: 9000
  access_key: WRc6I2ubSt9iZ0P6
  secret_key: AOm7m0CaFaeO5RW74jhzYEvxB6A0FK4P
