mongodb:
  host: avib-mongodb.default.svc.cluster.local
  port: 27017
  authentication-database: admin
  database: configuration
  username: root
  password: 46cfdg1oXL

minio:
  host: uniovi-hl.default.svc.cluster.local
  port: 9000
  access_key: BLBZSkLGtFD63XmP
  secret_key: vY8jARXmV7tsp7HSmtuBPjzBy8BWG57s